Remove build.py script and replace it with native CMSIS Solution build

diff --git a/.github/workflows/cmsis_rv2.yml b/.github/workflows/cmsis_rv2.yml
--- a/.github/workflows/cmsis_rv2.yml
+++ b/.github/workflows/cmsis_rv2.yml
@@ -20,10 +20,15 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        compiler: [AC6, GCC, Clang, IAR]
+        compiler: [AC6, GCC, CLANG, IAR]
         rtos: [RTX5, FreeRTOS]
+        device: [CM0plus, CM3, CM4, CM7, CM23, CM33, CM55, CM85]
 
     runs-on: ubuntu-24.04
+
+    env:
+      FVP_EXEC: ${{ fromJSON('{"CM0plus":"FVP_MPS2_Cortex-M0plus","CM3":"FVP_MPS2_Cortex-M3","CM4":"FVP_MPS2_Cortex-M4","CM7":"FVP_MPS2_Cortex-M7","CM23":"FVP_MPS2_Cortex-M23","CM33":"FVP_MPS2_Cortex-M33","CM55":"FVP_MPS2_Cortex-M55","CM85":"FVP_MPS2_Cortex-M85"}')[matrix.device] }}
+      IMG_EXT: ${{ fromJSON('{"AC6":"axf","GCC":"elf","CLANG":"elf","IAR":"out"}')[matrix.compiler] }}
 
     steps:
       - uses: actions/checkout@v6
@@ -49,15 +54,6 @@ jobs:
         with:
           repository: ARM-software/CMSIS-FreeRTOS
           path: CMSIS-FreeRTOS
-
-      - uses: actions/setup-python@v6
-        with:
-          python-version: '3.13'
-          cache: 'pip'
-
-      - name: Python requirements
-        run: |
-          pip install -r ./CMSIS-RTOS2_Validation/Project/requirements.txt
 
       - name: Install tools
         uses: ARM-software/cmsis-actions/vcpkg@v1
@@ -92,14 +88,21 @@ jobs:
         working-directory: ./CMSIS-RTOS2_Validation/Project
         run: |
           echo "Build test projects ..."
-          ./build.py --verbose -r ${{ matrix.rtos }} -c ${{ matrix.compiler }} build || echo "::warning::=== Some configurations failed to build! ==="
+          cbuild Validation.csolution.yml --packs --update-rte \
+            --toolchain ${{ matrix.compiler }} \
+            --context .${{ matrix.rtos }}+${{ matrix.device }} \
+            || echo "::warning::=== Some configurations failed to build! ==="
 
       - name: Execute
         if: env.ARM_UBL_ACTIVATION_CODE
         working-directory: ./CMSIS-RTOS2_Validation/Project
         run: |
           echo "Run test projects ..."
-          ./build.py --verbose -r ${{ matrix.rtos }} -c ${{ matrix.compiler }} run || echo "::warning::==== Some configurations failed to run! ==="
+          ${{ env.FVP_EXEC }} -q --simlimit 100 \
+            -f ../Layer/Board/${{ matrix.device }}/fvp_config.txt \
+            -a out/Validation/${{ matrix.device }}/${{ matrix.rtos }}/Validation.${{ env.IMG_EXT }} \
+            > Validation-${{ matrix.rtos }}-${{ matrix.device }}-${{ matrix.compiler }}.junit \
+            || echo "::warning::==== Some configurations failed to run! ==="
 
       - name: Deactivate Arm tool license
         if: always()
@@ -118,7 +121,7 @@ jobs:
         if: ${{ !cancelled() && env.ARM_UBL_ACTIVATION_CODE }}
         uses: actions/upload-artifact@v7
         with:
-          name: test-results-${{ matrix.rtos }}-${{ matrix.compiler }}
+          name: test-results-${{ matrix.rtos }}-${{ matrix.device }}-${{ matrix.compiler }}
           path: ./CMSIS-RTOS2_Validation/Project/*.junit
 
 
